apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "objecttypes.fullname" . }}
  labels:
    {{- include "objecttypes.labels" . | nindent 4 }}
data:
  DJANGO_SETTINGS_MODULE: "objecttypes.conf.docker"
  ALLOWED_HOSTS: {{ .Values.settings.allowedHosts | quote }}
  DB_HOST: {{ .Values.settings.database.host | toString | quote }}
  DB_PORT: {{ .Values.settings.database.port | toString | quote }}
  DB_USER: {{ .Values.settings.database.username | toString | quote }}
  DB_NAME: {{ .Values.settings.database.name | toString | quote }}
  PGSSLMODE: {{ .Values.settings.database.sslmode | toString | quote }}
  CACHE_DEFAULT: {{ .Values.settings.cache.default | toString | quote }}
  CACHE_AXES: {{ .Values.settings.cache.axes | toString | quote }}
  TWO_FACTOR_FORCE_OTP_ADMIN: {{ .Values.settings.twoFactorForceOtpAdmin | toString | quote }}
  TWO_FACTOR_PATCH_ADMIN: {{ .Values.settings.twoFactorPatchAdmin | toString | quote }}
  {{- if .Values.settings.admins }}
  ADMINS: {{ .Values.settings.admins | toString | quote }}
  {{- end }}
  {{- if .Values.settings.subPath }}
  SUBPATH: {{ .Values.settings.subPath | toString | quote }}
  {{- end }}
  {{- if .Values.settings.siteId }}
  SITE_ID: {{ .Values.settings.siteId | toString | quote }}
  {{- end }}
